"""add_character_traits_fields

Revision ID: 3f7e10f713f3
Revises: 2026_04_14_001
Create Date: 2026-04-14 22:44:39.387534
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f7e10f713f3'
down_revision: Union[str, None] = '2026_04_14_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('traits', sa.JSON(), nullable=True, comment='性格参数 5 维 {strictness, pace, questioning, warmth, humor}'))
    op.add_column('characters', sa.Column('system_prompt_template', sa.Text(), nullable=True, comment='自定义 system prompt 模板'))
    op.add_column('characters', sa.Column('template_name', sa.String(length=50), nullable=True, comment='角色模板 key，如 socrates/einstein'))
    op.add_column('characters', sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否可用于教学（DD1: 替代 TeacherPersona.is_active）'))
    op.alter_column('characters', 'experience_points',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('characters', 'level',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('characters', 'experience_points',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('characters', 'is_active')
    op.drop_column('characters', 'template_name')
    op.drop_column('characters', 'system_prompt_template')
    op.drop_column('characters', 'traits')
    # ### end Alembic commands ###
