from __future__ import annotations

import argparse
import os
import shutil


def rollback_database(db_path: str, backup_path: str) -> None:
    if not os.path.exists(backup_path):
        raise FileNotFoundError(f"Backup file not found: {backup_path}")

    shutil.copy2(backup_path, db_path)


def main() -> None:
    parser = argparse.ArgumentParser(description="Rollback Phase 1 migration from backup")
    parser.add_argument("--db", required=True, help="Target sqlite database path")
    parser.add_argument("--backup", required=True, help="Backup file path generated by migration script")
    args = parser.parse_args()

    rollback_database(args.db, args.backup)
    print(f"Rollback complete: restored {args.db} from {args.backup}")


if __name__ == "__main__":
    main()
