#!/usr/bin/env bash
#
# setup.sh — 苏格拉底学习系统一键初始化
#
# Usage: bash scripts/setup.sh

set -euo pipefail

echo ""
echo "=== 苏格拉底学习系统 初始化 ==="
echo ""

# 前置检查
for cmd in docker; do
    command -v "$cmd" &>/dev/null || { echo "❌ 需要安装 $cmd"; exit 1; }
done
docker compose version &>/dev/null || { echo "❌ 需要 Docker Compose v2"; exit 1; }

# 端口冲突检测
check_port() {
    local port=$1 service=$2
    if lsof -i ":$port" &>/dev/null 2>&1 || ss -ltn 2>/dev/null | grep -q ":$port "; then
        echo "⚠️  端口 $port 已被占用（$service 需要）"
        lsof -i ":$port" 2>/dev/null | head -5 || true
        echo ""
        read -p "是否尝试停止占用进程？(y/N) " confirm
        if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
            lsof -ti ":$port" | xargs kill 2>/dev/null || true
            sleep 1
            if lsof -i ":$port" &>/dev/null 2>&1; then
                echo "⚠️  进程仍在运行，尝试强制停止..."
                lsof -ti ":$port" | xargs kill -9 2>/dev/null || true
                sleep 1
            fi
            if lsof -i ":$port" &>/dev/null 2>&1; then
                echo "❌ 无法释放端口 $port，请手动处理。"
                exit 1
            fi
            echo "✅ 端口 $port 已释放"
        else
            echo "请手动释放端口 $port 后重试。"
            exit 1
        fi
    fi
}

check_port 80 "Frontend (Nginx)"
check_port 8000 "Backend (FastAPI)"

# 检查 .env 是否已存在
if [[ -f .env ]]; then
    read -p ".env 已存在，是否覆盖？(y/N) " confirm
    [[ "$confirm" != "y" && "$confirm" != "Y" ]] && echo "取消。" && exit 0
    echo ""
    echo "⚠️  密码将重新生成。如果之前已部署过，必须重置数据库卷："
    echo "   docker compose down -v"
    echo "   （这会删除所有数据库数据）"
    echo ""
    read -p "是否自动执行 docker compose down -v？(y/N) " reset
    if [[ "$reset" == "y" || "$reset" == "Y" ]]; then
        docker compose down -v 2>/dev/null || true
        echo "✅ 旧数据卷已清除"
    fi
fi

# 自动生成密钥（python3 优先，openssl fallback）
gen_hex() {
    local len=$1
    python3 -c "import secrets; print(secrets.token_hex($len))" 2>/dev/null \
        || openssl rand -hex "$len"
}

SECRET_KEY=$(gen_hex 32)
POSTGRES_PASSWORD=$(gen_hex 16)

# 交互式询问
read -p "前端访问地址 [http://localhost]: " CORS_ORIGIN
CORS_ORIGIN=${CORS_ORIGIN:-http://localhost}

# 写入 .env
cat > .env << ENVEOF
# Auto-generated by setup.sh at $(date)
SECRET_KEY=${SECRET_KEY}
CORS_ORIGIN=${CORS_ORIGIN}

# PostgreSQL
POSTGRES_USER=socratic
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=socratic_learning

# Neo4j (optional)
NEO4J_USER=neo4j
NEO4J_PASSWORD=${POSTGRES_PASSWORD}
KNOWLEDGE_GRAPH_ENABLED=false

# Sentry (optional)
# SENTRY_DSN=
ENVEOF

echo ""
echo "✅ .env 已生成"
echo ""
read -p "是否立即启动？(Y/n) " start
if [[ "$start" != "n" && "$start" != "N" ]]; then
    echo "正在构建并启动服务..."
    docker compose up -d --build
    echo ""
    echo "✅ 服务已启动"
    echo "  访问 ${CORS_ORIGIN}"
    echo "  LLM API Key 请在网页设置页配置"
else
    echo "下一步："
    echo "  docker compose up -d --build"
    echo "  访问 ${CORS_ORIGIN}"
    echo "  LLM API Key 请在网页设置页配置"
fi
echo ""
