#!/usr/bin/env bash
#
# setup.sh — 苏格拉底学习系统一键初始化
#
# Usage: bash scripts/setup.sh

set -euo pipefail

echo ""
echo "=== 苏格拉底学习系统 初始化 ==="
echo ""

# 前置检查
for cmd in docker; do
    command -v "$cmd" &>/dev/null || { echo "❌ 需要安装 $cmd"; exit 1; }
done
docker compose version &>/dev/null || { echo "❌ 需要 Docker Compose v2"; exit 1; }

# 检查 .env 是否已存在
if [[ -f .env ]]; then
    read -p ".env 已存在，是否覆盖？(y/N) " confirm
    [[ "$confirm" != "y" && "$confirm" != "Y" ]] && echo "取消。" && exit 0
fi

# 自动生成密钥（python3 优先，openssl fallback）
gen_hex() {
    local len=$1
    python3 -c "import secrets; print(secrets.token_hex($len))" 2>/dev/null \
        || openssl rand -hex "$len"
}

SECRET_KEY=$(gen_hex 32)

# 交互式询问
read -p "前端访问地址 [http://localhost]: " CORS_ORIGIN
CORS_ORIGIN=${CORS_ORIGIN:-http://localhost}
read -p "Sentry DSN（可留空）: " SENTRY_DSN

# 本地目录初始化
mkdir -p data backend/static/characters

# 写入 .env
cat > .env << ENVEOF
# Auto-generated by setup.sh at $(date)
SECRET_KEY=${SECRET_KEY}
CORS_ORIGIN=${CORS_ORIGIN}
DATABASE_URL=sqlite:///./data/socratic_learning.db

# Sentry (optional)
SENTRY_DSN=${SENTRY_DSN}
ENVEOF

echo ""
echo "✅ .env 已生成"
echo "✅ data 与静态目录已初始化"
echo ""
read -p "是否立即启动？(Y/n) " start
if [[ "$start" != "n" && "$start" != "N" ]]; then
    echo "正在构建并启动服务..."
    docker compose up -d --build
    echo ""
    echo "✅ 服务已启动"
    echo "  访问 ${CORS_ORIGIN}"
    echo "  LLM API Key 请在网页设置页配置"
else
    echo "下一步："
    echo "  docker compose up -d --build"
    echo "  访问 ${CORS_ORIGIN}"
    echo "  LLM API Key 请在网页设置页配置"
fi
echo ""
